name: 'apolitical_data_lead'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ['models']
# Seeds not needed - data loaded directly into DuckDB

models:
  apolitical_data_lead:
    base:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
