name: 'course_engagement'
version: '1.0.0'
config-version: 2

profile: 'course_engagement'

model-paths: ['models']
# Seeds not needed - data loaded directly into DuckDB

models:
  course_engagement:
    base:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
